//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodePool) DeepCopyInto(out *GPUNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodePool) DeepCopy() *GPUNodePool {
	if in == nil {
		return nil
	}
	out := new(GPUNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GPUNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodePoolList) DeepCopyInto(out *GPUNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodePoolList) DeepCopy() *GPUNodePoolList {
	if in == nil {
		return nil
	}
	out := new(GPUNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GPUNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodePoolSpec) DeepCopyInto(out *GPUNodePoolSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderConfig, len(*in))
		copy(*out, *in)
	}
	in.Requirements.DeepCopyInto(&out.Requirements)
	out.Scaling = in.Scaling
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(PoolLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodePoolSpec) DeepCopy() *GPUNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodePoolStatus) DeepCopyInto(out *GPUNodePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodePoolStatus) DeepCopy() *GPUNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPURequirementsSpec) DeepCopyInto(out *GPURequirementsSpec) {
	*out = *in
	if in.GPUTypes != nil {
		in, out := &in.GPUTypes, &out.GPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPURequirementsSpec) DeepCopy() *GPURequirementsSpec {
	if in == nil {
		return nil
	}
	out := new(GPURequirementsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *RayConfig) DeepCopyInto(out *RayConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *RayConfig) DeepCopy() *RayConfig {
	if in == nil {
		return nil
	}
	out := new(RayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	if in.RayConfig != nil {
		in, out := &in.RayConfig, &out.RayConfig
		*out = new(RayConfig)
		**out = **in
	}
	if in.ModelConfig != nil {
		in, out := &in.ModelConfig, &out.ModelConfig
		*out = new(ModelConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PoolLimits) DeepCopyInto(out *PoolLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PoolLimits) DeepCopy() *PoolLimits {
	if in == nil {
		return nil
	}
	out := new(PoolLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodeClaim) DeepCopyInto(out *GPUNodeClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodeClaim) DeepCopy() *GPUNodeClaim {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GPUNodeClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodeClaimList) DeepCopyInto(out *GPUNodeClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodeClaimList) DeepCopy() *GPUNodeClaimList {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GPUNodeClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodeClaimSpec) DeepCopyInto(out *GPUNodeClaimSpec) {
	*out = *in
	in.Requirements.DeepCopyInto(&out.Requirements)
	if in.PodRefs != nil {
		in, out := &in.PodRefs, &out.PodRefs
		*out = make([]PodReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodeClaimSpec) DeepCopy() *GPUNodeClaimSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodeClaimStatus) DeepCopyInto(out *GPUNodeClaimStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionedAt != nil {
		in, out := &in.ProvisionedAt, &out.ProvisionedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.IdleSince != nil {
		in, out := &in.IdleSince, &out.IdleSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodeClaimStatus) DeepCopy() *GPUNodeClaimStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ClaimRequirements) DeepCopyInto(out *ClaimRequirements) {
	*out = *in
	if in.GPUTypes != nil {
		in, out := &in.GPUTypes, &out.GPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ClaimRequirements) DeepCopy() *ClaimRequirements {
	if in == nil {
		return nil
	}
	out := new(ClaimRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PodReference) DeepCopyInto(out *PodReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PodReference) DeepCopy() *PodReference {
	if in == nil {
		return nil
	}
	out := new(PodReference)
	in.DeepCopyInto(out)
	return out
}
